spring:
  datasource:
    druid:
      master:
        url: jdbc:mysql://localhost:3306/macula-tinyid?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password:
        initialSize: 2
        maxActive: 20
        minIdle: 2
        maxWait: 10000

server:
  port: 8082
  servlet:
    encoding:
      force: true
    context-path: /tinyid