server:
  port: 9000

spring:
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 10.94.108.55:8848
        # namespace:
        # group:
    gateway:
      routes:
        - id: macula-cloud-system
          uri: http://localhost:8081
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
        - id: macula-cloud-tinyid
          uri: lb://macula-cloud-tinyid
          predicates:
            - Path=/tinyid/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: ${spring.application.name}
          client-secret: gateway
          introspection-uri: http://localhost:8081/api/token/introspect
  redis:
    database: 0
    host: 10.94.108.61
    port: 6380
    password: maculaV5@2023
macula:
  security:
    ignore-urls:
      - /tinyid/**
      - /system/api/token
      - /system/api/token/introspect
    only-auth-urls: /mall/api/**

logging:
  level:
    com.alibaba.nacos.client: error
    dev.macula.cloud.gateway: debug
    org.springframework.boot: debug
