spring:
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848
        namespace: MACULA5
        # group:
    gateway:
      routes:
        - id: macula-cloud-system
          uri: lb://macula-cloud-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          #client-id: e4da4a32-592b-46f0-ae1d-784310e88423
          #client-secret: secret
          #introspection-uri: http://127.0.0.1:9010/oauth2/introspect
          client-id: opp-admin
          client-secret: 5UbCsPTMwPOTAZe6y8CBVUpHSMtougkS
          introspection-uri: https://goauth-dev.infinitus.com.cn/introspect
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    system:
      database: 0
      host: 127.0.0.1
      port: 6379

macula:
  gateway:
    security:
      only-auth-urls: /mallapi/**
      ignore-urls:
        - /system/api/token
        - /system/api/token/introspect

logging:
  level:
    root: info
    dev.macula.cloud: debug
  file:
    name: ${user.home}/logs/${spring.application.name}/${spring.application.name}.log
