server:
  port: 9000

spring:
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848
        # namespace:
        # group:
    gateway:
      routes:
        - id: macula-cloud-system
          uri: lb://macula-cloud-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
        - id: macula-cloud-tinyid
          uri: lb://macula-cloud-tinyid
          predicates:
            - Path=/tinyid/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: ${spring.application.name}
          client-secret: gateway
          introspection-uri: https://goauth-dev.infinitus.com.cn/introspect
macula:
  security:
    ignore-urls: /tinyid/**
    only-auth-urls: /mall/api/**

logging:
  level:
    com.alibaba.nacos.client: error
    dev.macula.cloud.gateway: debug
    org.springframework.boot: debug