spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.94.108.56:3306/macula_system?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: maculav5
    password: maculaV5@2023
  redis:
    database: 0
    host: 10.94.108.61
    port: 6380
    password: maculaV5@2023
  cache:
    # 缓存类型 redis、none(不使用缓存)
    type: redis
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 10.94.108.55:8848
        # namespace:
        # group:
    sentinel:
      enabled: false
macula:
  security:
    ignore-urls:
      - /api/**
      - /swagger-ui/index.html
      - /v3/api-docs/swagger-config
system:
  tenant:
    table:
      containsTenantTables:
        - sys_application
        - sys_dept
        - sys_dict_item
        - sys_menu

mybatis-plus:
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

feign:
  httpclient:
    enabled: false
    max-connections: 200 # 线程池最大连接数，默认200
    time-to-live: 900 # 线程存活时间，单位秒，默认900
    connection-timeout: 2000  # 新建连接超时时间，单位ms, 默认2000
    follow-redirects: true # 是否允许重定向，默认true
    disable-ssl-validation: false # 是否禁止SSL检查， 默认false
    okhttp:
      read-timeout: 60s # 请求超时时间，Duration配置方式
  okhttp:
    enabled: true

seata:
  enabled: false

springdoc:
  api-docs:
    enabled: true  # 默认是true，用于开关API文档
  swagger-ui:
    enabled: true # 默认是true，用于开关API UI

server:
  port: 8081
  servlet:
    encoding:
      force: true

logging:
  level:
    com.alibaba.nacos.client: error
    dev.macula.cloud: debug
    org.springframework: info
